apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <your-acm-certificate-arn>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 5678
      protocol: TCP
  selector:
    service: n8n
